packages:
  - "packages/nastech-app"
  - "packages/nastech-agent"
  - "packages/nastech-cli"
  - "packages/nastech-server"
  - "packages/nastech-wire"
  - "packages/nastech-app-logs"
  - "packages/codium"
