apiVersion: v1
kind: Service
metadata:
  name: nastech-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: nastech-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nastech-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nastech-postgres
  template:
    metadata:
      labels:
        app: nastech-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: nastech
            - name: POSTGRES_PASSWORD
              value: nastech
            - name: POSTGRES_DB
              value: nastech
