apiVersion: v1
kind: Secret
metadata:
  name: handy-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://nastech:nastech@nastech-postgres:5432/nastech
  NASTECH_MASTER_SECRET: local-dev-secret-not-for-production
  S3_HOST: nastech-minio
  S3_PORT: "9000"
  S3_USE_SSL: "false"
  S3_ACCESS_KEY: minioadmin
  S3_SECRET_KEY: minioadmin
  S3_BUCKET: nastech
